package com.m00v13.tv;

import android.content.Context;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import java.io.BufferedInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;

public final class RealDebridClient {
    public static final String OPEN_SOURCE_CLIENT_ID="X245A4XAIBGVM";
    private static final String OAUTH="https://api.real-debrid.com/oauth/v2/",REST="https://api.real-debrid.com/rest/1.0/";
    private static final int CONNECT_TIMEOUT_MS=10000,READ_TIMEOUT_MS=15000;
    private final Context context;private final DebridStore store;
    public static final class InfringingSourceException extends IOException{InfringingSourceException(String m){super(m);}}
    public static final class RateLimitedException extends IOException{public final int retrySeconds;RateLimitedException(String m,int s){super(m);retrySeconds=s;}}
    public static final class TransientApiException extends IOException{TransientApiException(String m){super(m);}}
    public static final class DeviceCode{public final String deviceCode,userCode,verificationUrl;public final int intervalSeconds,expiresInSeconds;DeviceCode(String d,String u,String v,int i,int e){deviceCode=d;userCode=u;verificationUrl=v;intervalSeconds=i;expiresInSeconds=e;}}
    public static final class UserCredentials{public final String clientId,clientSecret;UserCredentials(String i,String s){clientId=i;clientSecret=s;}}
    public RealDebridClient(Context c){context=c.getApplicationContext();store=new DebridStore(context);}

    public DeviceCode beginDeviceAuth()throws Exception{JSONObject o=getJson(OAUTH+"device/code?client_id="+enc(OPEN_SOURCE_CLIENT_ID)+"&new_credentials=yes",null,false);return new DeviceCode(o.getString("device_code"),o.getString("user_code"),o.getString("verification_url"),Math.max(5,o.optInt("interval",5)),Math.max(60,o.optInt("expires_in",1800)));}
    public UserCredentials pollUserCredentials(String deviceCode)throws Exception{Response r=request("GET",OAUTH+"device/credentials?client_id="+enc(OPEN_SOURCE_CLIENT_ID)+"&code="+enc(deviceCode),null,null,false);int ec=errorCode(r.body);String em=errorText(r.body);if(r.code==403||r.code==404)return null;if(r.code==429||ec==5||ec==34)throw new RateLimitedException(em.isEmpty()?"Real-Debrid asked us to slow down":em,10);if(r.code>=500)throw new TransientApiException("Real-Debrid service HTTP "+r.code);require2xx(r);JSONObject o=new JSONObject(r.body);String id=o.optString("client_id",""),s=o.optString("client_secret","");return id.isEmpty()||s.isEmpty()?null:new UserCredentials(id,s);}
    public void finishDeviceAuth(DeviceCode code,UserCredentials c)throws Exception{store.saveCredentials(c.clientId,c.clientSecret);saveTokenResponse(postFormJson(OAUTH+"token","client_id",c.clientId,"client_secret",c.clientSecret,"code",code.deviceCode,"grant_type","http://oauth.net/grant_type/device/1.0"));}
    public String ensureAccessToken()throws Exception{String x=store.accessToken();if(x!=null&&System.currentTimeMillis()+60000L<store.accessExpiresAtMs())return x;String id=store.clientId(),sec=store.clientSecret(),ref=store.refreshToken();if(id==null||sec==null||ref==null)throw new IOException("Real-Debrid is not connected");saveTokenResponse(postFormJson(OAUTH+"token","client_id",id,"client_secret",sec,"code",ref,"grant_type","http://oauth.net/grant_type/device/1.0"));x=store.accessToken();if(x==null)throw new IOException("Real-Debrid token refresh failed");return x;}

    public List<SourceOption> probeCache(List<SourceOption> input,int maxProbes)throws Exception{if(input==null||input.isEmpty()||maxProbes<=0)return input;final String token=ensureAccessToken();int workers=SearchConcurrency.forJobs(context,Math.min(maxProbes,input.size()));ExecutorService pool=Executors.newFixedThreadPool(workers);ArrayList<Future<SourceOption>> fs=new ArrayList<>();int[] budget={0};for(SourceOption source:input){final boolean should=source.cached==null&&source.uri!=null&&source.uri.startsWith("magnet:")&&budget[0]++<maxProbes;fs.add(pool.submit(()->{Boolean cached=source.cached;try{if(should)cached=probeMagnetCached(source.uri,token);}catch(InfringingSourceException e){DebugLog.append(context,"DEBRID","Filtered infringing source from "+source.provider);return null;}int score=source.score+(Boolean.TRUE.equals(cached)?1200:Boolean.FALSE.equals(cached)?-40:0);return new SourceOption(source.provider,source.releaseName,source.uri,source.quality,source.videoCodec,source.hdr,source.audioCodec,source.audioLayout,source.audioLanguages,source.subtitleLanguages,source.sizeBytes,source.seeders,cached,score);}));}ArrayList<SourceOption> out=new ArrayList<>();for(Future<SourceOption> f:fs)try{SourceOption s=f.get();if(s!=null)out.add(s);}catch(Exception e){DebugLog.append(context,"DEBRID","Cache probe failed: "+shortMessage(e));}pool.shutdownNow();out.sort(Comparator.comparingInt((SourceOption s)->s.score).reversed().thenComparing(Comparator.comparingInt((SourceOption s)->s.seeders).reversed()));return out;}
    private Boolean probeMagnetCached(String magnet,String token)throws InfringingSourceException{String id=null;try{JSONObject added=postAuthorizedForm(REST+"torrents/addMagnet",token,"magnet",magnet);id=added.optString("id","");if(id.isEmpty())return null;JSONObject info=getJson(REST+"torrents/info/"+encPath(id),token,true);String file=chooseBestVideoFile(info.optJSONArray("files"));if(file==null)return null;postAuthorizedFormAllowEmpty(REST+"torrents/selectFiles/"+encPath(id),token,"files",file);for(int i=0;i<3;i++){info=getJson(REST+"torrents/info/"+encPath(id),token,true);JSONArray links=info.optJSONArray("links");if("downloaded".equals(info.optString("status"))&&links!=null&&links.length()>0)return Boolean.TRUE;String s=info.optString("status","");if("downloading".equals(s)||"queued".equals(s))return Boolean.FALSE;if("error".equals(s)||"magnet_error".equals(s)||"virus".equals(s)||"dead".equals(s))return Boolean.FALSE;Thread.sleep(250);}return Boolean.FALSE;}catch(InfringingSourceException e){throw e;}catch(Exception e){return null;}finally{if(id!=null&&!id.isEmpty())try{delete(REST+"torrents/delete/"+encPath(id),token);}catch(Exception ignored){}}}
    public String resolveMagnet(String magnet)throws Exception{if(magnet==null||!magnet.startsWith("magnet:"))throw new IOException("Not a magnet source");String token=ensureAccessToken();JSONObject added=postAuthorizedForm(REST+"torrents/addMagnet",token,"magnet",magnet);String id=added.optString("id","");if(id.isEmpty())throw new IOException("Real-Debrid did not return a torrent id");boolean keep=false;try{JSONObject info=getJson(REST+"torrents/info/"+encPath(id),token,true);String file=chooseBestVideoFile(info.optJSONArray("files"));if(file==null)throw new IOException("No playable video file found in torrent");postAuthorizedFormAllowEmpty(REST+"torrents/selectFiles/"+encPath(id),token,"files",file);JSONObject ready=null;for(int i=0;i<12;i++){info=getJson(REST+"torrents/info/"+encPath(id),token,true);JSONArray links=info.optJSONArray("links");if("downloaded".equals(info.optString("status"))&&links!=null&&links.length()>0){ready=info;break;}String s=info.optString("status","");if("error".equals(s)||"magnet_error".equals(s)||"virus".equals(s)||"dead".equals(s))throw new IOException("Real-Debrid torrent status: "+s);Thread.sleep(650);}if(ready==null)throw new IOException("Source is not instantly available in debrid cache");String restricted=ready.getJSONArray("links").getString(0);JSONObject u=postAuthorizedForm(REST+"unrestrict/link",token,"link",restricted);String download=u.optString("download","");if(download.isEmpty())throw new IOException("Real-Debrid returned no playable URL");keep=true;return download;}finally{if(!keep)try{delete(REST+"torrents/delete/"+encPath(id),token);}catch(Exception ignored){}}}

    private String chooseBestVideoFile(JSONArray files)throws JSONException{if(files==null)return null;long best=-1;String id=null;for(int i=0;i<files.length();i++){JSONObject f=files.getJSONObject(i);String p=f.optString("path","").toLowerCase(Locale.US);if(!isVideo(p))continue;long b=f.optLong("bytes",0);if(b>best){best=b;id=String.valueOf(f.optLong("id"));}}return id;}private static boolean isVideo(String p){return p.endsWith(".mkv")||p.endsWith(".mp4")||p.endsWith(".m4v")||p.endsWith(".webm")||p.endsWith(".avi")||p.endsWith(".ts")||p.endsWith(".m2ts");}
    private void saveTokenResponse(JSONObject t)throws Exception{String a=t.optString("access_token",""),r=t.optString("refresh_token","");long e=t.optLong("expires_in",3600);if(a.isEmpty()||r.isEmpty())throw new IOException("Incomplete Real-Debrid token response");store.saveTokens(a,r,e);}
    private JSONObject getJson(String u,String t,boolean a)throws Exception{Response r=request("GET",u,null,t,a);require2xx(r);return new JSONObject(r.body);}private JSONObject postFormJson(String u,String...p)throws Exception{Response r=request("POST",u,form(p),null,false);require2xx(r);return new JSONObject(r.body);}private JSONObject postAuthorizedForm(String u,String t,String...p)throws Exception{Response r=request("POST",u,form(p),t,true);require2xx(r);return r.body.trim().isEmpty()?new JSONObject():new JSONObject(r.body);}private void postAuthorizedFormAllowEmpty(String u,String t,String...p)throws Exception{Response r=request("POST",u,form(p),t,true);if(r.code==202||(r.code>=200&&r.code<300))return;require2xx(r);}private void delete(String u,String t)throws Exception{Response r=request("DELETE",u,null,t,true);require2xx(r);}
    private static final class Response{final int code;final String body;Response(int c,String b){code=c;body=b;}}
    private Response request(String method,String url,String body,String token,boolean auth)throws IOException{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(CONNECT_TIMEOUT_MS);c.setReadTimeout(READ_TIMEOUT_MS);c.setRequestMethod(method);c.setRequestProperty("Accept","application/json");c.setRequestProperty("User-Agent","M00V13/0.1 AndroidTV");if(auth&&token!=null)c.setRequestProperty("Authorization","Bearer "+token);if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");byte[] b=body.getBytes(StandardCharsets.UTF_8);c.setFixedLengthStreamingMode(b.length);try(OutputStream o=c.getOutputStream()){o.write(b);}}int code=c.getResponseCode();InputStream raw=code>=400?c.getErrorStream():c.getInputStream();String response=raw==null?"":read(raw);c.disconnect();return new Response(code,response);}
    private static String read(InputStream raw)throws IOException{try(InputStream in=new BufferedInputStream(raw);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[4096];int n;while((n=in.read(b))>=0){out.write(b,0,n);if(out.size()>2*1024*1024)throw new IOException("API response too large");}return new String(out.toByteArray(),StandardCharsets.UTF_8);}}
    private static void require2xx(Response r)throws IOException{if(r.code>=200&&r.code<300)return;int ec=errorCode(r.body);String e=errorText(r.body),m="HTTP "+r.code+(e.isEmpty()?"":": "+e)+(ec>=0?" (code "+ec+")":"");String lower=(m+" "+r.body).toLowerCase(Locale.US);if(ec==35||lower.contains("infring"))throw new InfringingSourceException("Real-Debrid rejected infringing file");if(r.code==429||ec==5||ec==34)throw new RateLimitedException(m,10);if(r.code>=500)throw new TransientApiException(m);throw new IOException(m);}private static int errorCode(String body){try{return new JSONObject(body).optInt("error_code",-1);}catch(Exception e){return -1;}}private static String errorText(String body){try{return new JSONObject(body).optString("error","");}catch(Exception e){return "";}}
    private static String form(String...p)throws Exception{if(p.length%2!=0)throw new IllegalArgumentException("form requires key/value pairs");List<String> parts=new ArrayList<>();for(int i=0;i<p.length;i+=2)parts.add(enc(p[i])+"="+enc(p[i+1]));return join(parts,"&");}private static String join(List<String>v,String sep){StringBuilder b=new StringBuilder();for(int i=0;i<v.size();i++){if(i>0)b.append(sep);b.append(v.get(i));}return b.toString();}private static String enc(String v)throws Exception{return URLEncoder.encode(v,"UTF-8");}private static String encPath(String v)throws Exception{return URLEncoder.encode(v,"UTF-8").replace("+","%20");}private static String shortMessage(Throwable t){Throwable x=t;while(x.getCause()!=null)x=x.getCause();String m=x.getMessage();return m==null?x.getClass().getSimpleName():m;}
}
