plugins { id 'com.android.application' }

android {
    namespace 'com.m00v13.tv'
    compileSdk 36
    buildToolsVersion '36.0.0'

    defaultConfig {
        applicationId 'com.m00v13.tv'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '0.1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.media3:media3-exoplayer:1.11.0'
    implementation 'androidx.media3:media3-ui:1.11.0'
    implementation 'org.jsoup:jsoup:1.23.2'
    implementation 'com.google.zxing:core:3.5.4'
}
